#  𝒒𝒑𝒓𝒐𝒋-- copyright (c) the contributors
#  SPDX-License-Identifier: MIT OR Apache-2.0

#  𝒒𝒑𝒓𝒐𝒋 -- copyright (c) the contributors
#  SPDX-License-Identifier: MIT OR Apache-2.0


[tool.black]
line-length = 80
include = "scripts/.*.py"
exclude = "__pycache__/.*"

[tool.pyright]
include = ["scripts"]
exclude = ["**/__pycache__"]
