#  𝒒𝒑𝒓𝒐𝒋 -- copyright (c) the contributors
#  SPDX-License-Identifier: MIT OR Apache-2.0


[toolchain]
# Keep in sync with bevy.
channel = "nightly-2025-06-25" # nightly version on the day 1.88.0 stabilized
targets = ["x86_64-pc-windows-msvc", "x86_64-unknown-linux-gnu"]
components = [
    "rustc-codegen-cranelift",
    "clippy",
    "rustc",
    "cargo",
    "rust-analyzer",
    "rustfmt",
]
