[package]
name = "worldgen" 
version = "0.1.0"
publish = false
authors = ["<phoenix.mandala@pm.me>"] 
edition = "2021"

[features]
# just to silence the warning
debug = ["debug_gizmos"]
dev = ["bevy/dynamic_linking"]

[dependencies]
bevy = {workspace = true}
noise = "0.9.0"
serde = { version = "1.0.217", features = ["derive"] }
rand = {workspace = true}
itertools = {workspace = true}
log = {workspace = true}
serde_json = "1.0.138"
debug_gizmos = {workspace = true, optional = true}
rayon= {workspace = true}