[package]
name = "worldgen" 
version = "0.1.0"
publish = false
authors = ["<phoenix.mandala@pm.me>"] 
edition = "2021"

[features]
dev = [
    "bevy/dynamic_linking",
]
debug = ["debug_gizmos"]

[dependencies]
noise = "0.9.0"
serde = { version = "1.0.217", features = ["derive"] }
bevy = {workspace =  true}
bevy_kira_audio = {workspace = true}
bevy_asset_loader = {workspace = true}
rand = {workspace = true}
itertools = {workspace = true}
log = {workspace = true}
serde_json = "1.0.138"
debug_gizmos = {workspace = true, optional = true}