#          •
#  ┏┓┏┓┏┓┏┓┓
#  ┗┫┣┛┛ ┗┛┃
# --┗┛-----┛------------------------------------------ (c) 2025 contributors ---
# Linux builds
[target.nightly-x86_64-unknown-linux-gnu]
linker = "mold"
rustflags = [
    # Nightly
    "-Zshare-generics=y",
    "-Zthreads=0",
    # Mold linker
    #
    # You may need to install it:
    #
    # - Ubuntu: `sudo apt-get install mold clang`
    # - Fedora: `sudo dnf install mold clang`
    # - Arch: `sudo pacman -S mold clang`
    "-Clink-arg=-fuse-ld=/usr/bin/mold",
]
