[package]
name = "player" 
version = "0.1.0"
publish = false
authors = ["<phoenix.mandala@pm.me>"] 
edition = "2021"

[features]
debug = ["debug_gizmos"]
dev = ["bevy/dynamic_linking"]

[dependencies]
bevy = {workspace = true}
serde = { version = "1.0.217", features = ["derive"] }
rand = {workspace = true}
itertools = {workspace = true}
log = {workspace = true}
serde_json = "1.0.138"
debug_gizmos = {workspace = true, optional = true}
anyhow = {workspace = true}
derivative = {workspace = true}
thiserror = {workspace = true}
bevy_flycam = "0.15.0"
