# ------------------------------------------
# SPDX-License-Identifier: MIT OR Apache-2.0
# -------------------------------- 𝒒𝒑𝒓𝒐𝒋 --
[profile.default]
slow-timeout = { period = "5s", terminate-after = 3 }
