#!/bin/bash

. ./.env

CHECK="--check"
if [[ $* == *--fix* ]]; then
  FIX="--fix"
  CHECK=""
fi

set -e
./scripts/headers.sh
cargo clippy --locked --workspace -F debug -F inspector $FIX -- --no-deps $ALLOWED
cargo fmt -- $CHECK
