#!/bin/bash

. ./.env

CHECK="--check"
if [[ $* == *--fix*  ]]; then FIX="--fix"; CHECK=""; fi

set -e
./scripts/headers.sh
cargo clippy --no-deps --locked --workspace -F debug -F inspector $FIX -- $ALLOWED
cargo fmt -- $CHECK