#!/bin/bash
# This script installs xwin.
# See the bevy cheatbook for more info.
# https://bevy-cheatbook.github.io/setup/cross/linux-windows.html

if [[ $* == *-f* || $* == *--force* ]]; then
  FORCE=true
fi
if [[ $* == *-x* || $* == *--xwin* ]]; then
  XWIN=true
fi
if [[ $* == *-b* || $* == *--bin* ]]; then
  BIN=true
fi

if [[ $XWIN || $FORCE || ! -d ".xwin-cache" ]]; then
  cargo install xwin --locked
  xwin --accept-license splat
fi

# from https://jake-shadle.github.io/xwin/#4-override-cc-defaults
if [[ $BIN || $FORCE || ! -d ".bin" ]]; then
    rm -rf .bin
    mkdir .bin > /dev/null
    ln -s /usr/bin/clang .bin/clang-cl
    ln -s /usr/bin/llvm-ar .bin/llvm-lib
    ln -s /usr/bin/lld-link .bin/lld-link
    clang-cl -v;
    llvm-lib -v;
    lld-link --version;
fi

cat <<EOF
Successfully set up.
If you want to debug with windbg or renderdoc, make sure that they are in your path,\
then run \`cargo wsl\` with \`WINDBG=true\` or \`RENDERDOC=true\`.

!IMPORTANT! If you are running a Debian-based distro, you will need to set Clang as your C(++) compiler.\
Run the following:\
\
    update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100;\
    update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 100;\

EOF