name: Cargo Build & Test

on:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86-64-pc-windows-msvc, x86_64-unknown-linux-gnu ] #TODO: MacOS?
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: ./scripts/cargo-chk
