name: Cargo Build & Test

on:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        target: [x86_64-pc-windows-msvc] #, x86_64-unknown-linux-gnu ] #TODO: MacOS?
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install bevy build deps
        run: sudo apt update &&
          sudo apt install -y pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 llvm clang lld

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{matrix.target}}
          components: rustfmt,clippy
          rustflags: ""
        
      - name: cache xwin
        uses: actions/cache@v4
        if: ${{matrix.target}} == x86_64-pc-windows-msvc
        with:
          path: .xwin-cache
          key: ${{ runner.OS }}-xwin-cache # doesn't need to hash

      - run: "./scripts/cargo-setup"
        if: ${{matrix.target}} == x86_64-pc-windows-msvc 

      - run: curl -sfL https://direnv.net/install.sh | bash
      - run: direnv allow
      - run: direnv export gha >> "$GITHUB_ENV"
      - run: env
      
      - name: cargo chk
        run: ./scripts/cargo-chk
      # TODO: This isn't linking. Missing symbols from meshopt crate. Mysterious and not worth
      # investigating until later.
      - name: cargo build (${{matrix.target}})
        run: cargo build --release --target=${{matrix.target}}
      # TODO add tests
      # TODO zip up bin and assets, upload artefact
